name: AI NSE Stock Prediction

on:
  schedule:
    - cron: '45 3 * * 1-5'

  workflow_dispatch:

jobs:

  predict:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create folders
        run: |
          mkdir -p cache
          mkdir -p reports

      - name: Run Prediction
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python main.py

      - uses: actions/upload-artifact@v4
        with:
          name: prediction-report
          path: reports/*.xlsx
